# Generated by Django 6.0.4 on 2026-05-04 04:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('two_fa_enabled', models.BooleanField(default=False)),
                ('two_fa_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin',
                'indexes': [models.Index(fields=['email'], name='admin_email_07aef7_idx'), models.Index(fields=['account_status'], name='admin_account_1c0101_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('user_type', models.CharField(choices=[('tamu', 'Tamu'), ('pegawai', 'Pegawai'), ('admin', 'Admin')], max_length=20)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
                ('table_name', models.CharField(max_length=255)),
                ('record_id', models.CharField(max_length=255)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['user_id', 'timestamp'], name='audit_log_user_id_835db7_idx'), models.Index(fields=['table_name', 'record_id'], name='audit_log_table_n_38ccfb_idx'), models.Index(fields=['timestamp'], name='audit_log_timesta_e8e14e_idx')],
            },
        ),
        migrations.CreateModel(
            name='CalendarSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('daily_quota', models.IntegerField(default=50)),
                ('is_holiday', models.BooleanField(default=False)),
                ('holiday_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'calendar_settings',
                'indexes': [models.Index(fields=['date'], name='calendar_se_date_0861ad_idx'), models.Index(fields=['is_holiday'], name='calendar_se_is_holi_f6cfeb_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('user_type', models.CharField(choices=[('tamu', 'Tamu'), ('pegawai', 'Pegawai'), ('admin', 'Admin')], max_length=20)),
                ('success', models.BooleanField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'login_attempt',
                'indexes': [models.Index(fields=['email', 'timestamp'], name='login_attem_email_ad1639_idx'), models.Index(fields=['ip_address', 'timestamp'], name='login_attem_ip_addr_c30e68_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_id', models.CharField(max_length=255)),
                ('sender_type', models.CharField(choices=[('pegawai', 'Pegawai'), ('tamu', 'Tamu')], max_length=20)),
                ('subject', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('read', 'Read'), ('replied', 'Replied'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('attachment_path', models.FileField(blank=True, null=True, upload_to='message_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'message',
                'indexes': [models.Index(fields=['sender_id', 'created_at'], name='message_sender__8e11cb_idx'), models.Index(fields=['status'], name='message_status_fbc084_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_id', models.CharField(max_length=255)),
                ('recipient_type', models.CharField(choices=[('tamu', 'Tamu'), ('pegawai', 'Pegawai'), ('admin', 'Admin')], max_length=20)),
                ('notification_type', models.CharField(choices=[('visit_registered', 'Visit Registered'), ('message_received', 'Message Received'), ('message_replied', 'Message Replied'), ('quota_reached', 'Quota Reached'), ('system_alert', 'System Alert')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read')], default='unread', max_length=20)),
                ('related_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notification',
                'indexes': [models.Index(fields=['recipient_id', 'created_at'], name='notificatio_recipie_04e032_idx'), models.Index(fields=['status'], name='notificatio_status_700f9c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pegawai',
                'indexes': [models.Index(fields=['email'], name='pegawai_email_8bc39d_idx'), models.Index(fields=['department'], name='pegawai_departm_bbfc37_idx'), models.Index(fields=['account_status'], name='pegawai_account_f03f82_idx')],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('user_type', models.CharField(choices=[('tamu', 'Tamu'), ('pegawai', 'Pegawai'), ('admin', 'Admin')], max_length=20)),
                ('session_token', models.CharField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'session',
                'indexes': [models.Index(fields=['user_id', 'expires_at'], name='session_user_id_36b6ba_idx'), models.Index(fields=['session_token'], name='session_session_f1d3ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tamu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('registration_type', models.CharField(choices=[('manual', 'Manual Registration'), ('google_sso', 'Google SSO')], default='manual', max_length=20)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tamu',
                'indexes': [models.Index(fields=['email'], name='tamu_email_b6319f_idx'), models.Index(fields=['google_id'], name='tamu_google__92b03e_idx'), models.Index(fields=['account_status'], name='tamu_account_abdd9d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Kunjungan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pegawai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kunjungan_diterima', to='guest_book.pegawai')),
                ('tamu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kunjungan', to='guest_book.tamu')),
            ],
            options={
                'db_table': 'kunjungan',
            },
        ),
        migrations.CreateModel(
            name='KunjunganNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_id', models.CharField(max_length=255)),
                ('author_type', models.CharField(choices=[('pegawai', 'Pegawai'), ('admin', 'Admin')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kunjungan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_history', to='guest_book.kunjungan')),
            ],
            options={
                'db_table': 'kunjungan_note',
                'indexes': [models.Index(fields=['kunjungan', 'created_at'], name='kunjungan_n_kunjung_d926df_idx')],
            },
        ),
        migrations.CreateModel(
            name='KunjunganStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_by_id', models.CharField(max_length=255)),
                ('changed_by_type', models.CharField(choices=[('pegawai', 'Pegawai'), ('admin', 'Admin')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('kunjungan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='guest_book.kunjungan')),
            ],
            options={
                'db_table': 'kunjungan_status_history',
                'indexes': [models.Index(fields=['kunjungan', 'changed_at'], name='kunjungan_s_kunjung_63eb3f_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reply_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guest_book.admin')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='guest_book.message')),
            ],
            options={
                'db_table': 'message_reply',
                'indexes': [models.Index(fields=['message', 'created_at'], name='message_rep_message_bd0106_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='kunjungan',
            index=models.Index(fields=['tamu', 'arrival_time'], name='kunjungan_tamu_id_faf274_idx'),
        ),
        migrations.AddIndex(
            model_name='kunjungan',
            index=models.Index(fields=['pegawai', 'arrival_time'], name='kunjungan_pegawai_0290b4_idx'),
        ),
        migrations.AddIndex(
            model_name='kunjungan',
            index=models.Index(fields=['status'], name='kunjungan_status_657ef5_idx'),
        ),
        migrations.AddIndex(
            model_name='kunjungan',
            index=models.Index(fields=['arrival_time'], name='kunjungan_arrival_dda999_idx'),
        ),
    ]
