# Generated by Django 6.0.4 on 2026-05-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamu',
            name='instansi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tamu',
            name='nik',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
