# Generated by Django 6.0.4 on 2026-05-05 13:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0002_tamu_instansi_tamu_nik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departemen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('kode', models.CharField(blank=True, max_length=50, null=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'departemen',
            },
        ),
        migrations.CreateModel(
            name='Instansi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(default='Institusi Teknologi Dirgantara', max_length=255)),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('status_operasional', models.CharField(default='Aktif', max_length=50)),
                ('jumlah_petugas', models.IntegerField(default=12)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'instansi',
            },
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_token',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='pegawai',
            name='department_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pegawai_list', to='guest_book.departemen'),
        ),
    ]
