# Generated by Django 6.0.4 on 2026-05-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0003_departemen_instansi_alter_pegawai_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instansi',
            name='kapasitas_maksimal',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='instansi',
            name='jumlah_petugas',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='instansi',
            name='nama',
            field=models.CharField(default='Diskominfosantik Kabupaten Bekasi', max_length=255),
        ),
    ]
