# Generated by Django 6.0.4 on 2026-05-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0004_instansi_kapasitas_maksimal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instansi',
            name='jam_buka',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='instansi',
            name='jam_tutup',
            field=models.TimeField(default='16:00'),
        ),
    ]
