# Generated by Django 6.0.4 on 2026-05-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0005_instansi_jam_buka_instansi_jam_tutup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instansi',
            name='kapasitas_maksimal',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='tamu',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
