# Generated by Django 6.0.4 on 2026-05-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0006_alter_instansi_kapasitas_maksimal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamu',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
