# Generated by Django 6.0.4 on 2026-05-08 01:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0007_tamu_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('sender_id', models.CharField(max_length=255)),
                ('sender_type', models.CharField(choices=[('admin', 'Admin'), ('tamu', 'Tamu'), ('pegawai', 'Pegawai')], max_length=20)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='departemen',
            options={'verbose_name': 'Bidang / Bagian', 'verbose_name_plural': 'Daftar Bidang / Bagian'},
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='department_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pegawai_list', to='guest_book.departemen', verbose_name='Bidang'),
        ),
    ]
