# Generated by Django 6.0.4 on 2026-05-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0008_chatmessage_alter_departemen_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(default='text', max_length=20),
        ),
    ]
