# Generated by Django 6.0.4 on 2026-05-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0009_chatmessage_attachment_chatmessage_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamu',
            name='jabatan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tamu',
            name='nip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
