# Generated by Django 6.0.4 on 2026-05-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0010_tamu_jabatan_tamu_nip'),
    ]

    operations = [
        migrations.AddField(
            model_name='instansi',
            name='hari_kerja',
            field=models.CharField(blank=True, default='0,1,2,3,4', max_length=50, null=True),
        ),
    ]
