# Generated by Django 6.0.4 on 2026-05-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0011_instansi_hari_kerja'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamu',
            name='admin_role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('operator', 'Operator')], default='operator', max_length=20),
        ),
    ]
